### ISSUE TITLE
messages not arriving in axolotl 

### ISSUE THREAD

**Issue by gurucubano** [nanu-c/axolotl#356]
### Description

I have installed the latest Axolotl Beta 0.9.6 in my BQ E4.5 UBports mobile and registered fine. 

But, signal messages to my number/account sent from my other phone (iPhone 14.0) never show up, also not when the two mobiles are on the same table and the Axolotl is up and running. And, when I try to send a message to any another well known number it always says:
```
Starting new chats is currently broken in Axolotl.
Please ask you conversation partner to start the chat first.
```

**Comment by nanu-c** [comment]
Dear gurucubano thank you for taking your time for reporting the issue. Please try to reset the session and attach the log file.

**Comment by gurucubano** [comment]
Hello manu-c, Thanks for your reply. But, I do not see in the Settings of the app, how to enable such session log. I ssh'ed into the mobile and see a proc `textsecure -e ut` running and could find its config file:
```
phablet@ubuntu-phablet:~$ cat ./.config/textsecure.nanuc/config.yml
tel: "+49176xxxxxxxxx"
uuid: ""
server: https://textsecure-service.whispersystems.org:443
rootCA: ""
proxy: ""
verificationType: sms
storageDir: /home/phablet/.local/share/textsecure.nanuc/.storage
unencryptedStorage: true
storagePassword: ""
loglevel: debug
userAgent: TextSecure 0.9.6 for Ubuntu Phone
alwaysTrustPeerID: true
accountCapabilities:
  uuid: true
  gv2: true
  storage: false
  gv1Migration: false
discoverableByPhoneNumber: false
```
I will attach the log file .cache/upstart/application-click-textsecure.nanuc_textsecure_0.9.6.log
[application-click-textsecure.nanuc_textsecure_0.9.6.log](https://github.com/nanu-c/axolotl/files/5938766/application-click-textsecure.nanuc_textsecure_0.9.6.log)
![axolotl](https://user-images.githubusercontent.com/8157672/107144429-62697f00-693b-11eb-9f09-320b87dcc023.jpg)
